server:
  port: 8888

spring:
  application:
    name: eshop-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liuziyuan/eshop-springcloud-containers/config-repository

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka